import {
  Activity,
  Bell,
  Bot,
  Database,
  GitBranch,
  LayoutDashboard,
  List,
  Shield,
  ShieldCheck,
  Users,
} from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

// ── Data ─────────────────────────────────────────────────────────────────
const dataFlow = [
  {
    title: "Ingestion",
    description:
      "Events arrive through two channels: the syslog collector (port 5140) that receives logs from firewalls, servers and applications, or remote (Python) agents that monitor endpoints and send logs via API with API key authentication.",
    icon: Database,
  },
  {
    title: "Normalization",
    description:
      "The pipeline parses raw logs and normalizes them into a structured format with common fields: timestamp, event type, severity, source IP and metadata.",
    icon: Activity,
  },
  {
    title: "Correlation",
    description:
      "The correlation engine evaluates each event against the active rules. Sigma-style rules detect patterns (e.g. SSH brute force) by counting occurrences within time windows.",
    icon: GitBranch,
  },
  {
    title: "Alerts",
    description:
      "When a rule matches, an alert is created or updated with severity, status and a count of related events. Alerts are grouped automatically by rule + source IP.",
    icon: Bell,
  },
  {
    title: "Analysis",
    description:
      "The analysis service complements the rules with anomaly detection (IsolationForest), z-score baselines and per-entity risk scoring.",
    icon: ShieldCheck,
  },
  {
    title: "Enrichment",
    description:
      "Threat Intelligence queries external providers (AbuseIPDB, AlienVault OTX, VirusTotal) to enrich indicators of compromise (IOCs) with reputation and context.",
    icon: Shield,
  },
  {
    title: "Notification",
    description:
      "When severity warrants it, notifiers send alerts via email (SMTP) or webhook (Slack/Discord) to notify the team without waiting for someone to open the dashboard.",
    icon: Bell,
  },
  {
    title: "Storage & querying",
    description:
      "All events, rules, alerts and agents are persisted in PostgreSQL. The SPA queries the data through the REST API with JWT authentication.",
    icon: Database,
  },
]

const appSections = [
  {
    title: "Dashboard",
    description:
      "Main view with live statistics: events per hour, severity distribution, alert metrics and the latest generated alerts.",
    icon: LayoutDashboard,
    path: "/",
  },
  {
    title: "Events",
    description:
      "Paged table of all normalized events with severity filtering. It's the raw detail of what the system is receiving.",
    icon: List,
    path: "/events",
  },
  {
    title: "Alerts",
    description:
      "Alerts generated by the correlation engine. You can change their status (open, investigating, resolved), export to CSV and view groupings.",
    icon: Bell,
    path: "/alerts",
  },
  {
    title: "Rules",
    description:
      "Sigma-style detection rules: condition, threshold and time window. Only admins can create them, enable/disable them or delete them.",
    icon: Shield,
    path: "/rules",
  },
  {
    title: "Agents",
    description:
      "Remote agent management: create agents with API keys, see their status and heartbeats. Restricted to admins.",
    icon: Bot,
    path: "/agents",
  },
  {
    title: "Users",
    description:
      "User CRUD with roles. Only admins can create users or deactivate them.",
    icon: Users,
    path: "/users",
  },
]

const roles = [
  {
    role: "Admin",
    permissions: [
      "Create, edit and delete rules",
      "Enable/disable rules",
      "Create and deactivate users",
      "Manage remote agents",
      "Everything an analyst can do",
    ],
  },
  {
    role: "Analyst",
    permissions: [
      "View dashboard, events and alerts",
      "Change alert status",
      "Export alerts to CSV",
      "Threat intel queries",
    ],
  },
]

// ── Help Page ───────────────────────────────────────────────────────────
export default function HelpPage() {
  return (
    <div className="space-y-8">
      {/* ── Header ───────────────────────────────────────────────────── */}
      <div>
        <h1 className="text-2xl font-bold">Help</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          How SentinelPy works: architecture, data flow, sections and roles.
        </p>
      </div>

      {/* ── What it is ───────────────────────────────────────────────── */}
      <Card>
        <CardHeader>
          <CardTitle>What is SentinelPy?</CardTitle>
          <CardDescription>
            Lightweight SIEM for SMBs — Python + FastAPI + React + PostgreSQL
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="leading-relaxed text-muted-foreground">
            SentinelPy is a Security Information and Event Management system
            designed for learning environments and small/medium businesses.
            It collects security events, normalizes them, runs correlation
            rules in real time and generates alerts with email/webhook
            notifications.
          </p>
        </CardContent>
      </Card>

      {/* ── Data flow ───────────────────────────────────────────────── */}
      <div>
        <h2 className="mb-4 text-lg font-semibold">How data flows</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {dataFlow.map((step, i) => (
            <Card key={step.title}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <span className="flex h-6 w-6 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">
                    {i + 1}
                  </span>
                  <step.icon className="h-4 w-4 text-primary" />
                  {step.title}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {step.description}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* ── Sections ────────────────────────────────────────────────── */}
      <div>
        <h2 className="mb-4 text-lg font-semibold">Application sections</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {appSections.map((section) => (
            <Card key={section.title}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <section.icon className="h-4 w-4 text-primary" />
                  {section.title}
                  <span className="ml-auto rounded-md bg-muted px-1.5 py-0.5 font-mono text-xs text-muted-foreground">
                    {section.path}
                  </span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {section.description}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* ── Roles ────────────────────────────────────────────────────── */}
      <div>
        <h2 className="mb-4 text-lg font-semibold">Roles and permissions</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {roles.map((r) => (
            <Card key={r.role}>
              <CardHeader>
                <CardTitle>{r.role}</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-1.5 text-sm text-muted-foreground">
                  {r.permissions.map((p) => (
                    <li key={p} className="flex items-start gap-2">
                      <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                      <span>{p}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* ── Key concepts ─────────────────────────────────────────────── */}
      <Card>
        <CardHeader>
          <CardTitle>Key concepts</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-6 sm:grid-cols-2">
            <div className="space-y-1.5">
              <p className="text-sm font-medium">Event</p>
              <p className="text-sm text-muted-foreground">
                A normalized log (login attempt, firewall connection, process,
                etc.) with structured fields. It is the base unit of
                information.
              </p>
            </div>
            <div className="space-y-1.5">
              <p className="text-sm font-medium">Rule</p>
              <p className="text-sm text-muted-foreground">
                A Sigma-style detection condition (e.g. "≥10 authentication
                failures within 5 minutes from one IP"). It defines which
                pattern to look for and with which severity to alert.
              </p>
            </div>
            <div className="space-y-1.5">
              <p className="text-sm font-medium">Alert</p>
              <p className="text-sm text-muted-foreground">
                The result of a rule match. It has a severity, a status and a
                count of related events. It can be grouped by rule + source IP.
              </p>
            </div>
            <div className="space-y-1.5">
              <p className="text-sm font-medium">Threat Intelligence</p>
              <p className="text-sm text-muted-foreground">
                Enrichment of indicators (IPs, hashes, domains) with external
                reputation from AbuseIPDB, AlienVault OTX and VirusTotal to
                prioritize investigations.
              </p>
            </div>
            <div className="space-y-1.5">
              <p className="text-sm font-medium">Remote agent</p>
              <p className="text-sm text-muted-foreground">
                Python asyncio client that monitors logs on an endpoint and
                sends them to the server via a secure API with rate limiting,
                local queue and heartbeats.
              </p>
            </div>
            <div className="space-y-1.5">
              <p className="text-sm font-medium">Temporal correlation</p>
              <p className="text-sm text-muted-foreground">
                The engine counts events of the same type within a time window
                (e.g. 10 minutes) and triggers the alert when the configured
                threshold is exceeded.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
