"""FastAPI application entry point.

Configures the app, registers routes, middlewares,
and handles the lifecycle (start/stop).
"""

import logging

from app.logging_config import setup_logging

setup_logging()

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.api import admin as admin_router
from app.api import agents as agents_router
from app.api import alerts, analysis, events, rules, stats
from app.api import auth as auth_router
from app.api import users as users_router
from app.config import settings
from app.middleware import register_error_handlers
from app.schemas.common import HealthResponse
from app.services.analysis_service import AnalysisService
from app.services.auth_service import AuthService
from app.services.engine import CorrelationEngine
from app.services.notifier import ConsoleNotifier, MultiNotifier
from app.services.pipeline import Pipeline

logger = logging.getLogger(__name__)

# ── Global instances ──────────────────────────────────────────────────
engine = CorrelationEngine()
multi_notifier = MultiNotifier()
pipeline = Pipeline(engine=engine)


async def crear_alerta_desde_engine(datos_alerta: dict) -> dict | None:
    """Callback that persists alerts generated by the correlation engine."""
    try:
        from app.database import async_session as db_session
        from app.models.alert import Alert

        async with db_session() as session:
            alerta = Alert(**datos_alerta)

            # Derive group_key from alert data
            source_ip = (
                datos_alerta.get("source_ip") or datos_alerta.get("source") or "unknown"
            )
            rule_id = str(alerta.rule_id)
            alerta.group_key = f"{rule_id}:{source_ip}"

            session.add(alerta)
            await session.commit()
            await session.refresh(alerta)

            alerta_dict = {
                "id": str(alerta.id),
                "rule_id": str(alerta.rule_id),
                "title": alerta.title,
                "severity": alerta.severity,
                "description": alerta.description,
                "status": alerta.status,
            }
            await multi_notifier.send_all(alerta_dict)
            logger.info(
                "Alert created by engine: %s | %s",
                alerta.title,
                alerta.severity,
            )
            return alerta_dict
    except Exception as e:
        logger.error("Error in alert callback: %s", e, exc_info=True)
        return None


async def actualizar_alerta_desde_engine(datos: dict):
    """Callback for updating counters within the time window.

    When the correlation engine detects an event within the time
    window of a rule, it calls this callback to increment event_count
    and update last_event_at on the existing alert.
    """
    try:
        from app.database import async_session as db_session
        from app.services.alert_service import AlertService

        async with db_session() as session:
            service = AlertService(session)
            await service.actualizar_contadores(
                rule_id=datos["rule_id"],
                event_count=datos["event_count"],
                last_event_at=datos["last_event_at"],
            )
    except Exception as e:
        logger.error("Error in update callback: %s", e, exc_info=True)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Handles the application lifecycle.

    Initializes DB, correlation engine, notifiers and collectors.
    """
    logger.info("Starting SentinelPy...")

    # ── Initialize database ────────────────────────────────────────
    try:
        from app.database import engine as db_engine
        from app.models.base import Base

        async with db_engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)

        logger.info("Database tables verified/created")

        # ── Seed admin user ──────────────────────────────────────────
        try:
            from app.database import async_session as db_session

            async with db_session() as seed_session:
                auth_svc = AuthService(seed_session)
                try:
                    admin_user = await auth_svc.crear_usuario(
                        username=settings.admin_username,
                        password=settings.admin_password,
                        role="admin",
                    )
                    logger.info("Admin created: %s", admin_user.username)
                except ValueError:
                    logger.info("Admin already exists, skipping seed")

                # ── Seed demo agent (for docker-compose) ────────────
                try:
                    import os as _os

                    from app.services.agent_service import AgentService

                    demo_key = _os.environ.get(
                        "AGENT_API_KEY", "spy_demo-key-change-me"
                    )
                    agent_svc = AgentService(seed_session)
                    existing = await agent_svc.obtener_por_api_key(demo_key)
                    if existing:
                        logger.info("Demo agent already exists with the correct key")
                    else:
                        # Look up by name — may have an old key
                        from sqlalchemy import select as _sel

                        from app.models.agent import Agent

                        result = await seed_session.execute(
                            _sel(Agent).where(Agent.name == "demo-agent")
                        )
                        found = result.scalar_one_or_none()
                        demo_hash = AuthService.hash_password(demo_key)
                        if found:
                            found.api_key_hash = demo_hash
                            found.active = True
                            await seed_session.commit()
                            logger.info(
                                "Demo agent: key updated from AGENT_API_KEY env"
                            )
                        else:
                            demo_agent = Agent(
                                name="demo-agent",
                                hostname="demo-agent",
                                api_key_hash=demo_hash,
                                active=True,
                            )
                            seed_session.add(demo_agent)
                            await seed_session.commit()
                            logger.info(
                                "Agente demo creado (key from AGENT_API_KEY env)"
                            )
                except Exception as e:
                    logger.warning("Could not seed demo agent: %s", e)
        except Exception as e:
            logger.warning("Could not seed admin: %s", e)
    except Exception as e:
        logger.warning("Could not connect to the database: %s", e)

    # ── Load rules into the correlation engine ─────────────────────────
    try:
        from app.database import async_session as db_session
        from app.services.rule_service import RuleService

        async with db_session() as session:
            rule_service = RuleService(session)
            reglas = await rule_service.cargar_reglas_activas()
            engine.cargar_reglas(reglas)

        engine.registrar_callback(crear_alerta_desde_engine)
        engine.registrar_callback_actualizar(actualizar_alerta_desde_engine)
        app.state.engine = engine
        logger.info("Correlation engine: %d active rules", engine.reglas_activas)
    except Exception as e:
        logger.warning("Could not initialize the correlation engine: %s", e)
        app.state.engine = None

    # ── Configure notifiers ─────────────────────────────────────────
    multi_notifier.agregar(ConsoleNotifier())

    # EmailNotifier (only if SMTP configuration exists)
    if settings.smtp_user:
        from app.services.email_notifier import EmailNotifier

        multi_notifier.agregar(
            EmailNotifier(), min_severity=settings.notify_min_severity
        )
        logger.info(
            "EmailNotifier configured for severity >= %s",
            settings.notify_min_severity,
        )

    # WebhookNotifier (only if a URL is configured)
    if settings.webhook_url:
        from app.services.webhook_notifier import WebhookNotifier

        multi_notifier.agregar(
            WebhookNotifier(), min_severity=settings.notify_min_severity
        )
        logger.info(
            "WebhookNotifier configured for severity >= %s",
            settings.notify_min_severity,
        )

    app.state.notifier = multi_notifier
    logger.info("Notifiers configured")

    # ── Initialize analysis service ─────────────────────────────────
    try:
        from app.database import async_session as db_session

        analysis_service = AnalysisService(db_session)
        await analysis_service.init_async()
        app.state.analysis_service = analysis_service
        pipeline.analysis_service = analysis_service
        logger.info("Analysis service initialized")
    except Exception as e:
        logger.warning("Could not initialize analysis: %s", e)
        app.state.analysis_service = None

    # ── Start syslog collector ──────────────────────────────────────────
    try:
        from app.services.collector import SyslogCollector

        colector = SyslogCollector(pipeline)
        await colector.start()
        app.state.colector = colector
        logger.info("Collection system started")
    except Exception as e:
        logger.warning("Could not start the syslog collector: %s", e)
        app.state.colector = None

    app.state.pipeline = pipeline
    logger.info("SentinelPy started successfully")

    yield  # La app corre

    # ── Graceful shutdown ────────────────────────────────────────────────
    logger.info("Stopping SentinelPy...")

    if hasattr(app.state, "colector") and app.state.colector:
        await app.state.colector.stop()
        logger.info("Collectors stopped")

    if hasattr(app.state, "analysis_service") and app.state.analysis_service:
        await app.state.analysis_service.shutdown()

    logger.info("SentinelPy stopped")


# ── FastAPI app creation ──────────────────────────────────────────
app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
    lifespan=lifespan,
)

# ── Static files (CSS, JS, images) ──────────────────────────────────────
import os

static_dir = os.path.join(os.path.dirname(__file__), "static")
os.makedirs(static_dir, exist_ok=True)
app.mount("/static", StaticFiles(directory=static_dir), name="static")

# ── Global error handlers ─────────────────────────────────────────────
register_error_handlers(app)

# ── API v1: all REST endpoints under /api/v1 ──────────────────────
from fastapi import APIRouter

v1_router = APIRouter(prefix="/api/v1")
v1_router.include_router(events.router)
v1_router.include_router(rules.router)
v1_router.include_router(alerts.router)
v1_router.include_router(auth_router.router)
v1_router.include_router(users_router.router)
v1_router.include_router(admin_router.router)
v1_router.include_router(analysis.router)
v1_router.include_router(stats.router)
app.include_router(v1_router)

# ── Backward compat: /api/ unversioned (deprecated, for tests) ─────
compat_router = APIRouter(prefix="/api")
compat_router.include_router(events.router)
compat_router.include_router(rules.router)
compat_router.include_router(alerts.router)
compat_router.include_router(auth_router.router)
compat_router.include_router(users_router.router)
compat_router.include_router(admin_router.router)
compat_router.include_router(analysis.router)
compat_router.include_router(stats.router)
app.include_router(compat_router)

# ── Agent endpoints (v2 — independently versioned) ────────────
app.include_router(agents_router.router)


# ── Health check (no auth, unversioned — for orchestrators) ────────
@app.get("/health", response_model=HealthResponse)
async def health():
    """Health check endpoint for Docker and orchestrators."""
    return HealthResponse(
        status="healthy",
        app=settings.app_name,
        version=settings.app_version,
        reglas_activas=engine.reglas_activas,
        ventanas_activas=engine.ventanas_activas,
    )


# ═════════════════════════════════════════════════════════════════════════
# WEB DASHBOARD PAGES (Server-Side Rendering)
# ═════════════════════════════════════════════════════════════════════════
# NOTE: The template routes were replaced by the SPA.
# The catch-all at the end of the file serves frontend/dist/index.html
# for all routes that do not match the API.


# ═════════════════════════════════════════════════════════════════════════
# SPA Catch-All — Serves the frontend for any non-API route
# ═════════════════════════════════════════════════════════════════════════
# IMPORTANT: This section must be at the END of the file, after
# ALL API routes.
#
# Approach: Route-based catch-all. FastAPI registers routes in order, so
# the API endpoints (`/api/*`, `/health`, etc.) match first.
# The `/{full_path:path}` at the end only captures what no previous
# endpoint matched — Vite static assets or SPA routes.
import os as _os

from fastapi.responses import FileResponse

_base = _os.path.dirname(__file__)
_spa_candidates = [
    _os.path.normpath(
        _os.path.join(_base, "..", "..", "frontend", "dist")
    ),  # local dev
    _os.path.normpath(_os.path.join(_base, "..", "frontend", "dist")),  # docker
]
_spa_dir = next((d for d in _spa_candidates if _os.path.isdir(d)), None)

if _spa_dir:
    _spa_index = _os.path.join(_spa_dir, "index.html")

    # MIME types for Vite assets
    _MIME_TYPES: dict[str, str] = {
        ".js": "application/javascript",
        ".mjs": "application/javascript",
        ".css": "text/css",
        ".json": "application/json",
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".svg": "image/svg+xml",
        ".ico": "image/x-icon",
        ".woff": "font/woff",
        ".woff2": "font/woff2",
        ".ttf": "font/ttf",
        ".eot": "application/vnd.ms-fontobject",
        ".webp": "image/webp",
        ".map": "application/json",
    }

    @app.get("/{full_path:path}", include_in_schema=False)
    async def serve_spa(full_path: str):
        """Serves static files from dist/ or falls back to index.html.

        API routes (`/api/*`) and explicit endpoints (`/health`,
        etc.) are already registered BEFORE this catch-all, so
        FastAPI matches them first and they never reach here.
        """
        # Serve the real file from dist/ if it exists
        candidate = _os.path.normpath(_os.path.join(_spa_dir, full_path))
        if _os.path.isfile(candidate):
            ext = _os.path.splitext(candidate)[1].lower()
            mime = _MIME_TYPES.get(ext, "application/octet-stream")
            return FileResponse(candidate, media_type=mime)

        # Fallback: index.html so React Router handles the route
        return FileResponse(_spa_index, media_type="text/html")

    logger.info("SPA catch-all active from: %s", _spa_dir)
else:
    logger.warning(
        "SPA directory not found. Searched in: %s. "
        "Run 'pnpm build' in frontend/ to serve the SPA.",
        _spa_candidates,
    )
